pipeline {
    agent any

    environment {
        SONARQUBE = 'sonar1'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-token', url: 'https://github.com/datnguyen101004/nt548_lab2_cau3.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('MySonarQube') {
                    sh 'mvn verify sonar:sonar'
                }
            }
        }

        stage('Build Docker Images') {
            parallel {
                stage('User Service') {
                    steps {
                        dir('user-service') {
                            sh 'docker build -t user-service:latest .'
                        }
                    }
                }
                stage('Blog Service') {
                    steps {
                        dir('blog-service') {
                            sh 'docker build -t blog-service:latest .'
                        }
                    }
                }
                stage('Api gateway') {
                    steps {
                        dir('api-gateway') {
                            sh 'docker build -t api-gateway:latest .'
                        }
                    }
                }
            }
        }

        stage('Deploy with Docker Compose') {
            steps {
                sh 'docker-compose down || true'
                sh 'docker-compose up -d'
            }
        }
    }
}
